"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080";
export function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const signup = mode === "signup"; const [message,setMessage] = useState(""); const [loading,setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const body = signup ? { ...data, role: "USER", provider: "LOCAL" } : data; try { const response = await fetch(`${API_URL}/api/v1/auth/${signup ? "signup" : "login"}`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body), credentials:"include" }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error?.message ?? "요청에 실패했습니다."); if (!signup && result.data?.accessToken) { localStorage.setItem("accessToken", result.data.accessToken); window.location.href="/"; return; } setMessage("가입이 완료됐어요. 이제 로그인해주세요!"); } catch(error) { setMessage(error instanceof Error ? error.message : "서버에 연결할 수 없습니다."); } finally { setLoading(false); } }
  return <form className="auth-form" onSubmit={submit}>{signup && <label>닉네임<input required name="nickname" placeholder="사용할 닉네임"/></label>}<label>이메일<input required name="email" type="email" placeholder="play@playon.kr"/></label><label>비밀번호<input required name="password" type="password" minLength={8} placeholder="8자 이상 입력해주세요"/></label>{!signup && <div className="auth-options"><label><input type="checkbox"/> 로그인 유지</label><button type="button">비밀번호 찾기</button></div>}<button className="auth-submit" disabled={loading}>{loading ? "잠시만요..." : signup ? "회원가입" : "로그인"}</button>{message && <p className="form-message">{message}</p>}<p className="auth-switch">{signup ? "이미 계정이 있나요?" : "아직 계정이 없나요?"} <Link href={signup ? "/login" : "/signup"}>{signup ? "로그인" : "회원가입"}</Link></p></form>;
}
