"use client";

import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Button, FormError, Select } from "@/components/ui";
import { RequireAuth } from "@/components/require-auth";
import { useAuth } from "@/lib/auth-context";
import { getMatchParticipants } from "@/lib/match";
import { submitReview } from "@/lib/user-service";
import type { MatchParticipantResponse } from "@/lib/types";

const RATINGS=[1,2,3,4,5];
export default function ReviewPage(){return <RequireAuth><ReviewForm/></RequireAuth>}
function ReviewForm(){const{matchId}=useParams<{matchId:string}>();const router=useRouter();const{user}=useAuth();const[people,setPeople]=useState<MatchParticipantResponse[]>([]);const[facilityRating,setFacilityRating]=useState(5);const[comment,setComment]=useState("");const[ratings,setRatings]=useState<Record<string,{manner:number;skill:number}>>({});const[error,setError]=useState<string>();const[saving,setSaving]=useState(false);useEffect(()=>{let active=true;getMatchParticipants(matchId).then(data=>{if(active)setPeople(data.filter(v=>v.userId!==user?.userId))}).catch(e=>{if(active)setError(e instanceof Error?e.message:"참가자를 불러오지 못했습니다.")});return()=>{active=false}},[matchId,user?.userId]);async function save(){if(!user)return;setSaving(true);setError(undefined);try{await submitReview(matchId,user.userId,{facilityReview:{rating:facilityRating,comment},participantReviews:people.map(person=>({revieweeId:person.userId,mannerRating:ratings[person.userId]?.manner??5,skillRating:ratings[person.userId]?.skill??5}))});router.replace("/mypage/matches")}catch(e){setError(e instanceof Error?e.message:"리뷰를 등록하지 못했습니다.")}finally{setSaving(false)}}return <main className="flow-page"><div className="flow-shell"><div className="flow-heading"><span>AFTER MATCH</span><h1>오늘 경기는 어떠셨나요?</h1><p>경기장과 함께한 플레이어에게 리뷰를 남겨주세요.</p></div><FormError message={error}/><section className="review-panel"><h2>경기장 평가</h2><Select value={facilityRating} onChange={e=>setFacilityRating(Number(e.target.value))}>{RATINGS.map(v=><option value={v} key={v}>{"★".repeat(v)} {v}.0</option>)}</Select><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={500} placeholder="경기장 이용 경험을 알려주세요."/></section><section className="review-panel"><h2>함께한 플레이어</h2>{people.length===0?<p className="record-empty">평가할 참가자가 없습니다.</p>:people.map((person)=><div className="participant-review" key={person.participantId}><div><b>{person.nickname || "알 수 없음"}</b><small>{person.role==="HOST"?"매치 호스트":"참가자"}</small></div><label>매너<Select value={ratings[person.userId]?.manner??5} onChange={e=>setRatings(current=>({...current,[person.userId]:{manner:Number(e.target.value),skill:current[person.userId]?.skill??5}}))}>{RATINGS.map(v=><option key={v} value={v}>{v}점</option>)}</Select></label><label>실력<Select value={ratings[person.userId]?.skill??5} onChange={e=>setRatings(current=>({...current,[person.userId]:{skill:Number(e.target.value),manner:current[person.userId]?.manner??5}}))}>{RATINGS.map(v=><option key={v} value={v}>{v}점</option>)}</Select></label></div>)}</section><Button type="button" loading={saving} onClick={save}>리뷰 등록하기</Button></div></main>}
