import Link from "next/link";
import { Header } from "@/components/header";
import { MatchActions } from "@/components/match-actions";
import { getMatch, getMatchParticipants } from "@/lib/api";

const sportLabel: Record<string, string> = { SOCCER: "축구", FUTSAL: "풋살", BASKETBALL: "농구", BADMINTON: "배드민턴", TENNIS: "테니스", VOLLEYBALL: "배구" };
const levelLabel: Record<string, string> = { BEGINNER: "초급", INTERMEDIATE: "중급", ADVANCED: "상급" };

export default async function MatchDetailPage({ params }: { params: Promise<{ matchId: string }> }) {
  const { matchId } = await params;
  const [match, participants] = await Promise.all([getMatch(matchId), getMatchParticipants(matchId)]);
  const deadline = new Date(match.recruitDeadline);
  const deadlineText = new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "long", day: "numeric", weekday: "short", hour: "2-digit", minute: "2-digit" }).format(deadline);
  const remaining = Math.max(0, match.capacity - match.currentCount);
  return <><Header/><main className="detail-page"><div className="container detail-breadcrumb"><Link href="/matches">매치 찾기</Link><span>›</span><b>{sportLabel[match.sportType] ?? match.sportType}</b></div><section className="container detail-layout"><div className="detail-main"><div className="detail-heading"><div><span className="detail-status">{match.status === "RECRUITING" ? "모집 중" : match.status}</span><span className="detail-sport">{sportLabel[match.sportType] ?? match.sportType}</span></div><h1>{match.title}</h1><p>모집 마감 {deadlineText}</p></div><div className="detail-art"><span>{match.sportType === "BASKETBALL" ? "🏀" : match.sportType === "BADMINTON" ? "🏸" : match.sportType === "TENNIS" ? "🎾" : "⚽"}</span><i/><i/></div><section className="detail-section"><h2>매치 정보</h2><div className="info-grid"><Info label="모집 인원" value={`${match.currentCount}/${match.capacity}명 · ${remaining}자리 남음`}/><Info label="참가 조건" value={`${levelLabel[match.minSkillLevel] ?? match.minSkillLevel} ~ ${levelLabel[match.maxSkillLevel] ?? match.maxSkillLevel}`}/><Info label="성별 조건" value={match.requiredGender === "ANY" ? "성별 무관" : match.requiredGender === "MALE" ? "남성" : "여성"}/><Info label="취소 마감" value={new Intl.DateTimeFormat("ko-KR", { month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(match.cancelDeadline))}/></div></section><section className="detail-section"><h2>함께하는 플레이어</h2><div className="participant-list">{participants.map((participant, index) => <div key={participant.participantId}><span>{String.fromCharCode(65 + index)}</span><div><b>{participant.role === "HOST" ? "매치 호스트" : `플레이어 ${index + 1}`}</b><small>{participant.role === "HOST" ? "HOST" : "참가 확정"}</small></div></div>)}{remaining > 0 && <div className="empty-player"><span>+</span><div><b>당신의 자리</b><small>지금 참가할 수 있어요</small></div></div>}</div></section><section className="detail-section facility-notice"><h2>경기 장소</h2><div><span>⌖</span><div><b>예약 경기장</b><p>예약 번호: {match.reservationId}</p><small>경기장 상세 정보는 예약 API 연결 후 표시됩니다.</small></div></div></section></div><aside className="join-card"><span>1인 참가비</span><strong>{match.feePerPerson.toLocaleString()}<small>원</small></strong><div className="join-progress"><div><span>현재 {match.currentCount}명</span><span>정원 {match.capacity}명</span></div><i><em style={{ width: `${Math.min(100, match.currentCount / match.capacity * 100)}%` }}/></i></div><div className="join-summary"><p><span>종목</span><b>{sportLabel[match.sportType]}</b></p><p><span>남은 자리</span><b className="coral-text">{remaining}자리</b></p><p><span>모집 마감</span><b>{deadlineText.split(" ").slice(0, 3).join(" ")}</b></p></div><MatchActions matchId={matchId} disabled={match.status !== "RECRUITING" || remaining === 0}/></aside></section></main></>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><b>{value}</b></div>; }
